# Generated by Django 3.0.8 on 2020-07-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200703_1523'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answervote',
            name='answer upvote',
        ),
        migrations.RemoveConstraint(
            model_name='questionvote',
            name='qa upvote',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='time',
        ),
    ]
